// Writes the Android TV string resources from the web catalogues, so a
// translation lives in one place. Run it after editing web/src/i18n.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const I18N_DIR = path.join(ROOT, "web", "src", "i18n");
const KEYS_FILE = path.join(ROOT, "android-tv", "strings.keys");
const RES_DIR = path.join(ROOT, "android-tv", "app", "src", "main", "res");

const HEADER = "<!-- Generated by scripts/android-strings.mjs from web/src/i18n. Do not edit. -->";
const FORM_ORDER = ["zero", "one", "two", "few", "many", "other"];

export const CATALOGUES = [
  { name: "en", file: "en", suffix: "" },
  { name: "cs", file: "cs", suffix: "-cs" },
  { name: "sk", file: "sk", suffix: "-sk" },
  { name: "de", file: "de", suffix: "-de" },
  { name: "es", file: "es", suffix: "-es" },
  { name: "fr", file: "fr", suffix: "-fr" },
  { name: "it", file: "it", suffix: "-it" },
  { name: "pl", file: "pl", suffix: "-pl" },
  { name: "ptBR", file: "ptBR", suffix: "-pt-rBR" },
  { name: "ru", file: "ru", suffix: "-ru" },
];

/** `auth.signedInAs` -> `auth_signed_in_as`: dots become underscores and each
 *  capital gains an underscore, which is how the Kotlin code already reads. */
export function resourceName(key) {
  return key.replace(/\./g, "_").replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

/** Placeholder order comes from the English text: the first distinct `{name}`
 *  is `%1$s`, the next `%2$s` and so on, whichever order a locale writes them. */
export function placeholderPositions(entry) {
  const texts = typeof entry === "string" ? [entry] : FORM_ORDER.filter((form) => entry[form] !== undefined).map((form) => entry[form]);
  const positions = new Map();
  for (const text of texts) {
    for (const match of text.matchAll(/\{(\w+)\}/g)) {
      if (!positions.has(match[1])) positions.set(match[1], positions.size + 1);
    }
  }
  return positions;
}

/** Replaces `{name}` with the positional Android placeholder. A name the
 *  English text never used has no position and stops the run. */
export function substitute(text, positions) {
  return text.replace(/\{(\w+)\}/g, (match, name) => {
    const position = positions.get(name);
    if (position === undefined) throw new Error(`placeholder {${name}} is not in the English text`);
    return `%${position}$s`;
  });
}

/** Android string escaping. The literal `%` becomes `%%` but a generated
 *  `%N$s` is left alone, so no resource needs `formatted="false"`. */
export function escapeAndroid(text) {
  let out = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/%(?!\d+\$s)/g, "%%")
    .replace(/\n/g, "\\n");
  if (out.startsWith("@") || out.startsWith("?")) out = `\\${out}`;
  return out;
}

/** One catalogue entry as the XML body, indented for `<resources>`. */
export function renderEntry(name, english, entry) {
  const positions = placeholderPositions(english);
  if (typeof english === "string") {
    if (typeof entry !== "string") throw new Error(`${name}: expected a string in this locale`);
    return `  <string name="${name}">${escapeAndroid(substitute(entry, positions))}</string>`;
  }
  const forms = FORM_ORDER.filter((form) => entry[form] !== undefined);
  const items = forms.map((form) => `    <item quantity="${form}">${escapeAndroid(substitute(entry[form], positions))}</item>`);
  return `  <plurals name="${name}">\n${items.join("\n")}\n  </plurals>`;
}

export function renderFile(keys, names, english, catalogue) {
  const body = keys.map((key, index) => renderEntry(names[index], english[key], catalogue[key]));
  return `<?xml version="1.0" encoding="utf-8"?>\n${HEADER}\n<resources>\n${body.join("\n")}\n</resources>\n`;
}

export function readKeys(file = KEYS_FILE) {
  return readFileSync(file, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"));
}

export function assertKeys(keys, english) {
  const missing = keys.filter((key) => !(key in english));
  if (missing.length > 0) throw new Error(`missing from en.ts: ${missing.join(", ")}`);
}

/** Reads the exported object literal out of a catalogue, for when Node cannot
 *  strip the file's types. The catalogues hold nothing but strings and nested
 *  forms, so the literal evaluates on its own. */
export function evalObjectLiteral(source, name) {
  const marker = source.search(new RegExp(`const\\s+${name}\\s*(?::[^=]+)?=`));
  const start = source.indexOf("{", marker);
  const end = source.lastIndexOf("}");
  if (marker < 0 || start < 0 || end < start) throw new Error(`could not find the ${name} catalogue literal`);
  return new Function(`return (${source.slice(start, end + 1)});`)();
}

export async function loadCatalogue({ name, file }) {
  const location = path.join(I18N_DIR, `${file}.ts`);
  try {
    const module = await import(pathToFileURL(location).href);
    return module[name];
  } catch (error) {
    console.warn(`Could not import ${path.relative(ROOT, location)} (${error.message}); evaluating the object literal instead.`);
    return evalObjectLiteral(readFileSync(location, "utf8"), name);
  }
}

export async function buildFiles() {
  const keys = readKeys();
  const names = keys.map(resourceName);
  const clashing = names.filter((name, index) => names.indexOf(name) !== index);
  if (clashing.length > 0) throw new Error(`two keys share a resource name: ${[...new Set(clashing)].join(", ")}`);

  const catalogues = new Map();
  for (const catalogue of CATALOGUES) catalogues.set(catalogue.name, await loadCatalogue(catalogue));

  const english = catalogues.get("en");
  assertKeys(keys, english);

  const files = new Map();
  for (const catalogue of CATALOGUES) {
    const target = path.join(RES_DIR, `values${catalogue.suffix}`, "strings.xml");
    try {
      files.set(target, renderFile(keys, names, english, catalogues.get(catalogue.name)));
    } catch (error) {
      throw new Error(`values${catalogue.suffix}: ${error.message}`);
    }
  }
  return files;
}

async function main() {
  const check = process.argv.includes("--check");
  const files = await buildFiles();
  let differs = false;
  for (const [target, content] of files) {
    let current;
    try {
      current = readFileSync(target, "utf8");
    } catch {
      current = undefined;
    }
    if (current === content) continue;
    differs = true;
    console.log(`${path.relative(ROOT, target)} ${check ? "differs" : "written"}`);
    if (!check) {
      mkdirSync(path.dirname(target), { recursive: true });
      writeFileSync(target, content);
    }
  }
  if (check && differs) {
    console.error("Android strings are stale; run `npm run android:strings`.");
    process.exitCode = 1;
  }
}

const isMain = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
